apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  scope: Namespaced
  group: otus.homework
  preserveUnknownFields: false
  versions:
  - name: v1
    served: true
    storage: true
  names:
    kind: MySQL
    plural: mysqls
    singular: mysql
    shortNames:
    - ms
  validation:
    openAPIV3Schema:
      required:
      - apiVersion
      - kind
      - metadata
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
        spec:
          type: object
          required:
          - password
          - database
          - storage_size
          properties:
            image: 
              type: string
            database:
              type: string
            password:
              type: string
            storage_size:
              type: string
